# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuessNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottos', models.CharField(max_length=24)),
                ('numbers', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
