# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessnumbers',
            name='name',
            field=models.CharField(default='John Doe', max_length=24),
            preserve_default=False,
        ),
    ]
