# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0003_auto_20161227_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuessNumbers',
        ),
    ]
