# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessnumbers',
            name='lottos',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
