# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0002_auto_20161227_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessnumbers',
            name='lottos',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
