# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0003_auto_20170608_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='Nick', max_length=255),
            preserve_default=False,
        ),
    ]
