# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import kilogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0005_auto_20170613_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=kilogram.models.user_path),
        ),
    ]
