# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0006_auto_20170613_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
