# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import kilogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0007_auto_20170613_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=kilogram.models.profile_path),
        ),
    ]
