# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilogram', '0008_auto_20170628_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
