# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0003_post_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
